# Generated by Django 5.2.1 on 2025-05-19 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0002_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draw_date', models.DateTimeField(auto_now_add=True)),
                ('is_claimed', models.BooleanField(default=False)),
                ('claim_date', models.DateTimeField(blank=True, null=True)),
                ('raffle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='raffles.raffle')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='raffles.ticket')),
            ],
        ),
    ]
