# Generated by Django 5.2.1 on 2025-05-19 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffle',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
